vim.g.mapleader=","
---noremap \ ,
vim.opt.syntax=on
vim.opt.tabstop=4
vim.opt.colorcolumn="80"
vim.opt.softtabstop=4
vim.opt.termguicolors=true
vim.opt.background="dark"
vim.opt.autoread=true
vim.opt.textwidth=0
vim.opt.showtabline=4
vim.opt.nu=true
vim.opt.cursorline=true
vim.opt.wildmenu=true
vim.opt.showmatch=true
vim.opt.incsearch=true
vim.opt.hlsearch=true
vim.opt.ignorecase=true
vim.opt.smartcase=true
vim.opt.history=1000
vim.opt.iskeyword:append("-")
vim.opt.title=true
vim.opt.formatoptions:append("1")
vim.opt.virtualedit="block"
vim.opt.mouse="a"
vim.opt.showcmd=true
vim.opt.autoindent=true
vim.opt.smartindent=true
vim.opt.shiftwidth=4
vim.opt.listchars={eol='¬',tab='>·',trail='~',extends='>',precedes='<',space='_'}
vim.opt.list=true
vim.opt.swapfile=false
vim.g.vim_markdown_folding_disabled=1
